name: Blog in Readme

on:
  workflow_dispatch:
  schedule:
    # Every day at “At 00:00.”
    - cron: 0 0 * * *

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: https://mrgkanev.eu/feed/
          committer_email: 41898282+github-actions[bot]@users.noreply.github.com
          committer_username: GitHub Actions[Bot]
