name: Blog in Readme
on:
  workflow_dispatch:
  schedule:
    # At 04:00 on Tuesday, Thursday, and Saturday
    - cron: '0 4 * * 2,4,6'
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: https://gkanev.com/feed/
          committer_email: 41898282+github-actions[bot]@users.noreply.github.com
          committer_username: GitHub Actions[Bot]
